### ISSUE TITLE
Downloads for stats not working

### ISSUE THREAD

**Issue by bmwhopper** [murraygm/Chrome-Medium-Stats-Grabber#1]
Hi, It seems that the downloading of stats has stopped working, im not sure if its an issue with the scrapper like in v1.3, upgraded to 1.4 still no joy

**Comment by murraygm** [comment]
Thanks for letting me know - I’ll take a look and see if there’s anything I
can do.

Sent from my iPhone

On Mar 5, 2019, at 03:32, bmwhopper <notifications@github.com> wrote:

Hi, It seems that the downloading of stats has stopped working, im not sure
if its an issue with the scrapper like in v1.3, upgraded to 1.4 still no joy

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/murraygm/Chrome-Medium-Stats-Grabber/issues/1>, or mute
the thread

**Comment by murraygm** [comment]
Fixed. Similar to last time, Medium tweaked their CSS. download v1.5
