### ISSUE TITLE
Adding Read Time

### ISSUE THREAD

**Issue by shinokada** [murraygm/Chrome-Medium-Stats-Grabber#3]
Firstly, thank you for your extension.

Is it possible to add "Read Time" field?

**Comment by murraygm** [comment]
Thanks @shinokada - the outputted data file has the date it was generated as the last part of the name. Are you looking for more granularity or do you want it in each row for convenience?

**Comment by shinokada** [comment]
Each article has a "Reading Time" or "readingTime" field and it is nice to have in your csv.

**Comment by murraygm** [comment]
The 'Reading time' is in the csv.file - it's under 'mins' but that justg gives you how long Medium thinks it will take to read the full article, if you want an approximation of 'actual' reading time you'll need to Reads*mins.
My basic use for this is to pull all the articles stats I can so that I can then dig into the trends over time. I'm not getting into individual article stats. I think you get them with the Medium Subscription.

**Comment by shinokada** [comment]
Thanks.
